name: Build ESP-IDF Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.0
          target: esp32c5

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: esp32c5-hello-world-build
          path: build/
